"""Init

Revision ID: 2f869b81d80c
Revises: 
Create Date: 2024-12-03 23:21:17.961097

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "2f869b81d80c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # TODO : 수정하기

    # 1. 임시 테이블 생성
    op.create_table(
        "account_new",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("name", sa.String(30)),
        sa.Column("number", sa.String(10)),
        sa.Column("product_code", sa.String(2)),
        sa.Column("app_key", sa.String(50)),
        sa.Column("secret_key", sa.String(100)),
        sa.Column("url_base", sa.String(100)),
        sa.Column("token", sa.String(200), nullable=True),
        sa.Column("broker_type", sa.CHAR(length=10), nullable=False),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
    )

    # 2. 데이터 복사
    op.execute(
        """
        INSERT INTO account_new (
            id, name, number, product_code, app_key, 
            secret_key, url_base, token
        )
        SELECT 
            id, name, number, product_code, app_key, 
            secret_key, url_base, token
        FROM account
    """
    )

    # 3. 기존 테이블 삭제
    op.drop_table("account")

    # 4. 새 테이블 이름 변경
    op.rename_table("account_new", "account")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "starategy",
        sa.Column("interval", infra.persistance.schema.IntervalType(), nullable=False),
    )
    op.add_column("starategy", sa.Column("last_run", sqlite.DATETIME(), nullable=True))

    op.alter_column(
        "account", "broker_type", existing_type=sa.CHAR(length=10), nullable=False
    )

    op.alter_column("starategy", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "starategy", "invest_rate", existing_type=sa.FLOAT(), nullable=False
    )

    op.drop_index("ix_starategy_id", table_name="starategy")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("starategy", "invest_rate", existing_type=sa.FLOAT(), nullable=True)
    op.alter_column("starategy", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "account", "broker_type", existing_type=sa.CHAR(length=10), nullable=True
    )

    op.create_index("ix_starategy_id", "starategy", ["id"], unique=False)

    op.drop_column("starategy", "last_run")
    op.drop_column("starategy", "interval")
    op.drop_column("starategy", "updated_at")
    op.drop_column("starategy", "created_at")
    op.drop_column("account", "updated_at")
    op.drop_column("account", "created_at")
    # ### end Alembic commands ###
